server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: car-service
              uri: lb://CAR-SERVICE
              predicates:
                - Path=/api/car/**
            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/booking/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**

